server:
  port: 9020
spring:
  application:
    name: zuul-demo
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:9011/eureka/
zuul:
  routes:
    eureka-client-demo1: /demo1/**

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 60000
